name: Russian, Windows, df-translate-hook

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache base pack
        uses: actions/cache@v2
        with:
          path: download
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('base_pack_url.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Install wget
      
      - name: Download base pack
        uses: wei/wget@v1
        with:
          args: -i base_pack_url.txt -O base_pack.zip
        run: |
          mkdir -p download
          mv base_pack.zip download/base_pack.zip
          touch download/base_pack.zip

      - name: Install python requirements
        run: make install_requirements

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
