name: Russian, Windows, df-translate-hook

on:
  # push:
  #   branches: [ master ]
  # pull_request:
  #  branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache base package
        uses: actions/cache@v2
        env:
          cache-name: cache-base-pack
        with:
          path: base_pack.zip
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('base_pack_url.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Set current time for the base_pack.zip restored from the cache
        if: steps.cache.outputs.cache-hit == 'true'
        run: touch base_pack.zip

      - name: Unpack base package
        run: |
          make base

      - name: Install python requirements
        run: |
          # sudo apt install python3-setuptools
          python3 -m pip install -U pip
          make install_requirements
