name: Russian, Windows, df-translate-hook

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache base pack
        uses: actions/cache@v2
        with:
          path: download
      
      - name: Download base pack
        run: make download

      - name: Install python requirements
        run: make install_requirements

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
