name: Russian, Windows, df-translate-hook

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache base package
        uses: actions/cache@v2
        env:
          cache-name: cache-base-pack
        with:
          path: base_pack.zip
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('base_pack_url.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Download base package
        run: make download

      - name: Unpack base package
        run: |
          touch base_pack.zip
          make base

      - name: Install python requirements
        run: |
          sudo apt install python3-setuptools
          python3 -m pip install -U pip
          make install_requirements

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
